import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useThemeStore } from '../stores/ThemeStore';
const LandingPage = () => {
    const { theme } = useThemeStore();
    return (_jsxs("div", { className: theme ? 'bg-gray-900 min-h-screen text-gray-200' : 'bg-gray-50 min-h-screen text-gray-800', children: [_jsx("section", { className: theme ? 'bg-gray-800 text-white py-20' : 'bg-blue-600 text-white py-20', children: _jsxs("div", { className: "container mx-auto px-6 text-center", children: [_jsx("h1", { className: "text-4xl md:text-5xl font-bold mb-4", children: "Real-Time Collaborative Editing" }), _jsx("p", { className: theme ? 'text-gray-200 text-lg md:text-xl mb-8' : 'text-white text-lg md:text-xl mb-8', children: "Edit documents together in real-time, export PDFs, and collaborate seamlessly using Yjs and Quill." }), _jsxs("div", { className: "flex justify-center space-x-4", children: [_jsx("button", { className: theme
                                        ? 'px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg shadow hover:bg-blue-700 transition'
                                        : 'px-6 py-3 bg-white text-blue-600 font-semibold rounded-lg shadow hover:bg-gray-100 transition', children: "Get Started" }), _jsx("button", { className: theme
                                        ? 'px-6 py-3 border border-gray-400 text-gray-200 font-semibold rounded-lg hover:bg-gray-700 hover:text-white transition'
                                        : 'px-6 py-3 border border-white text-white font-semibold rounded-lg hover:bg-white hover:text-blue-600 transition', children: "Learn More" })] })] }) }), _jsxs("section", { className: theme
                    ? 'py-20 container mx-auto px-6 bg-gray-900'
                    : 'py-20 container mx-auto px-6 bg-gray-50', children: [_jsx("h2", { className: theme
                            ? 'text-3xl font-bold text-center mb-12 text-white'
                            : 'text-3xl font-bold text-center mb-12 text-gray-800', children: "Platform Features" }), _jsxs("div", { className: "grid md:grid-cols-3 gap-10", children: [_jsxs("div", { className: theme
                                    ? 'bg-gray-800 p-6 rounded-lg shadow hover:shadow-lg transition'
                                    : 'bg-white p-6 rounded-lg shadow hover:shadow-lg transition', children: [_jsx("h3", { className: theme
                                            ? 'text-xl font-semibold mb-2 text-white'
                                            : 'text-xl font-semibold mb-2 text-gray-800', children: "Real-Time Collaboration" }), _jsxs("p", { className: theme ? 'text-gray-200' : 'text-gray-700', children: ["Multiple users can edit the same document simultaneously. Changes appear instantly using ", _jsx("span", { className: "font-semibold", children: "Yjs" }), " and", ' ', _jsx("span", { className: "font-semibold", children: "Quill" }), "."] })] }), _jsxs("div", { className: theme
                                    ? 'bg-gray-800 p-6 rounded-lg shadow hover:shadow-lg transition'
                                    : 'bg-white p-6 rounded-lg shadow hover:shadow-lg transition', children: [_jsx("h3", { className: theme
                                            ? 'text-xl font-semibold mb-2 text-white'
                                            : 'text-xl font-semibold mb-2 text-gray-800', children: "Export as PDF" }), _jsx("p", { className: theme ? 'text-gray-200' : 'text-gray-700', children: "Easily export your collaborative documents to PDF format, keeping all formatting intact. Perfect for sharing or printing." })] }), _jsxs("div", { className: theme
                                    ? 'bg-gray-800 p-6 rounded-lg shadow hover:shadow-lg transition'
                                    : 'bg-white p-6 rounded-lg shadow hover:shadow-lg transition', children: [_jsx("h3", { className: theme
                                            ? 'text-xl font-semibold mb-2 text-white'
                                            : 'text-xl font-semibold mb-2 text-gray-800', children: "Real-Time Updates & Versioning" }), _jsx("p", { className: theme ? 'text-gray-200' : 'text-gray-700', children: "Keep track of edits, undo changes, and maintain document history seamlessly. Collaborate without fear of losing data." })] })] })] }), _jsx("section", { className: theme ? 'bg-gray-900 py-20' : 'bg-gray-100 py-20', children: _jsxs("div", { className: "container mx-auto px-6", children: [_jsx("h2", { className: theme
                                ? 'text-3xl font-bold text-center mb-12 text-white'
                                : 'text-3xl font-bold text-center mb-12 text-gray-800', children: "How It Works" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-10 items-center", children: [_jsx("div", { children: _jsx("img", { src: "https://images.unsplash.com/photo-1581091215364-9b13e591fd1e?auto=format&fit=crop&w=800&q=80", alt: "Collaborative Editing", className: "rounded-lg shadow-lg" }) }), _jsxs("div", { className: "space-y-6", children: [_jsxs("p", { className: theme ? 'text-gray-200' : 'text-gray-700', children: ["Our platform leverages ", _jsx("span", { className: "font-semibold", children: "Yjs" }), " to synchronize changes across all users in real-time. No more conflicts or lost edits."] }), _jsxs("p", { className: theme ? 'text-gray-200' : 'text-gray-700', children: ["With ", _jsx("span", { className: "font-semibold", children: "Quill" }), ", you get a rich text editor experience. Format text, insert images, and see changes as they happen."] }), _jsx("p", { className: theme ? 'text-gray-200' : 'text-gray-700', children: "Export your documents as PDFs with a single click. Collaborate efficiently and deliver professional documents instantly." }), _jsx("button", { className: theme
                                                ? 'px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition'
                                                : 'px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition', children: "Try It Now" })] })] })] }) }), _jsxs("section", { className: "py-20 text-center", children: [_jsx("h2", { className: theme ? 'text-3xl font-bold mb-4 text-white' : 'text-3xl font-bold mb-4 text-gray-800', children: "Ready to Collaborate?" }), _jsx("p", { className: theme ? 'text-gray-200 mb-8' : 'text-gray-700 mb-8', children: "Join your team, start editing documents together, and experience seamless real-time collaboration." }), _jsx("button", { className: "px-8 py-4 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition", children: "Get Started for Free" })] }), _jsx("footer", { className: theme
                    ? 'bg-gray-800 text-white py-6 text-center'
                    : 'bg-gray-800 text-white py-6 text-center', children: _jsx("p", { children: "\u00A9 2025 Collaborative Platform. All rights reserved." }) })] }));
};
export default LandingPage;
